# Generated by Django 4.0 on 2023-07-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_campaign_id_alter_client_id_alter_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='campaign',
        ),
    ]
